### ISSUE TITLE
Server list requests data directly from servers to get player and game data.

### ISSUE THREAD

**Issue by Red-M** [ElDewrito/ElDewrito-MasterServer#2]
As per: https://github.com/vicelio/menu/issues/13

**Comment by Red-M** [comment]
Ok so since vicelio's repo is gone I will say it here again.

The browser pulls data from end user servers directly from inside the client browser of the joining player. This should be stored by the master server instead.

**Comment by emoose** [comment]
What's wrong with them querying the server themselves? Storing it on the master would be a lot of work, we'd have to write up stuff to sync the data between the server/master, and the master would need enough memory/storage to hold each servers info.

Why do all that when the client can query it themselves (which also has a side-benefit of giving the client the latest data, instead of something from the master which could be five minutes old)?

**Comment by dark-c0de** [comment]
This is exactly how Dorito menu works. It also acts like a master server, only sending updates to clients.

**Comment by preeefix** [comment]
@Red-M We've looked into this. The main push with the master servers is not to centralize the game too much. Having a smaller, less expensive (resources), servers that do a little bit less allows lower end servers (think Raspberry Pi level) to run the master servers.

Now if we had the master servers request the data, you'd need more resources to parse the data than tiny servers could handle, parsing the responses of potentially hundreds of servers every few moments can get taxing quick.

I'm keeping the issue open for discussion, as this may change in the future.

Edit: Didn't mean to close it...

**Comment by Shockfire** [comment]
Correct me if I'm wrong, but isn't it standard for server browsers in PC games to download info directly from the game server? You can potentially get stale information otherwise. The bottom line IMO is that if you can't even handle people pinging your server then you shouldn't be hosting.

**Comment by kiwidoggie** [comment]
It depends, for example in COD4 they "cached" it using gamespy etc, which the server would periodically update. But in Source, it pulls it all from server info.
